## xml

In [5]:
import urllib3
import requests
import xml.etree.ElementTree as et

In [6]:
LINK = "http://www.chilkatsoft.com/xml-samples/nutrition.xml"
response = requests.get(LINK)
with open('bookstore.xml', 'wb') as file:
    file.write(response.content)
filename = 'bookstore.xml'
file = open(filename, mode='r')
text = file.read()
print(file.closed)
file.close()
print(text)

False
<?xml version="1.0"?>
<nutrition>

<daily-values>
	<total-fat units="g">65</total-fat>
	<saturated-fat units="g">20</saturated-fat>
	<cholesterol units="mg">300</cholesterol>
	<sodium units="mg">2400</sodium>
	<carb units="g">300</carb>
	<fiber units="g">25</fiber>
	<protein units="g">50</protein>
</daily-values>

<food>
	<name>Avocado Dip</name>
	<mfr>Sunnydale</mfr>
	<serving units="g">29</serving>
	<calories total="110" fat="100"/>
	<total-fat>11</total-fat>
	<saturated-fat>3</saturated-fat>
	<cholesterol>5</cholesterol>
	<sodium>210</sodium>
	<carb>2</carb>
	<fiber>0</fiber>
	<protein>1</protein>
	<vitamins>
		<a>0</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>0</ca>
		<fe>0</fe>
	</minerals>
</food>

<food>
	<name>Bagels, New York Style </name>
	<mfr>Thompson</mfr>
	<serving units="g">104</serving>
	<calories total="300" fat="35"/>
	<total-fat>4</total-fat>
	<saturated-fat>1</saturated-fat>
	<cholesterol>0</cholesterol>
	<sodium>510</sodium>
	<carb>54</carb>
	<fiber>3</fiber>
	<protein>11</protein>
	<vitamins>
		<a>0</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>8</ca>
		<fe>20</fe>
	</minerals>
</food>

<food>
	<name>Beef Frankfurter, Quarter Pound </name>
	<mfr>Armitage</mfr>
	<serving units="g">115</serving>
	<calories total="370" fat="290"/>
	<total-fat>32</total-fat>
	<saturated-fat>15</saturated-fat>
	<cholesterol>65</cholesterol>
	<sodium>1100</sodium>
	<carb>8</carb>
	<fiber>0</fiber>
	<protein>13</protein>
	<vitamins>
		<a>0</a>
		<c>2</c>
	</vitamins>
	<minerals>
		<ca>1</ca>
		<fe>6</fe>
	</minerals>
</food>

<food>
	<name>Chicken Pot Pie</name>
	<mfr>Lakeson</mfr>
	<serving units="g">198</serving>
	<calories total="410" fat="200"/>
	<total-fat>22</total-fat>
	<saturated-fat>9</saturated-fat>
	<cholesterol>25</cholesterol>
	<sodium>810</sodium>
	<carb>42</carb>
	<fiber>2</fiber>
	<protein>10</protein>
	<vitamins>
		<a>20</a>
		<c>2</c>
	</vitamins>
	<minerals>
		<ca>2</ca>
		<fe>10</fe>
	</minerals>
</food>

<food>
	<name>Cole Slaw</name>
	<mfr>Fresh Quick</mfr>
	<serving units=" cup">1.5</serving>
	<calories total="20" fat="0"/>
	<total-fat>0</total-fat>
	<saturated-fat>0</saturated-fat>
	<cholesterol>0</cholesterol>
	<sodium>15</sodium>
	<carb>5</carb>
	<fiber>2</fiber>
	<protein>1</protein>
	<vitamins>
		<a>30</a>
		<c>45</c>
	</vitamins>
	<minerals>
		<ca>4</ca>
		<fe>2</fe>
	</minerals>
</food>

<food>
	<name>Eggs</name>
	<mfr>Goodpath</mfr>
	<serving units="g">50</serving>
	<calories total="70" fat="40"/>
	<total-fat>4.5</total-fat>
	<saturated-fat>1.5</saturated-fat>
	<cholesterol>215</cholesterol>
	<sodium>65</sodium>
	<carb>1</carb>
	<fiber>0</fiber>
	<protein>6</protein>
	<vitamins>
		<a>6</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>2</ca>
		<fe>4</fe>
	</minerals>
</food>

<food>
	<name>Hazelnut Spread</name>
	<mfr>Ferreira</mfr>
	<serving units="tbsp">2</serving>
	<calories total="200" fat="90"/>
	<total-fat>10</total-fat>
	<saturated-fat>2</saturated-fat>
	<cholesterol>0</cholesterol>
	<sodium>20</sodium>
	<carb>23</carb>
	<fiber>2</fiber>
	<protein>3</protein>
	<vitamins>
		<a>0</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>6</ca>
		<fe>4</fe>
	</minerals>
</food>

<food>
	<name>Potato Chips</name>
	<mfr>Lees</mfr>
	<serving units="g">28</serving>
	<calories total="150" fat="90"/>
	<total-fat>10</total-fat>
	<saturated-fat>3</saturated-fat>
	<cholesterol>0</cholesterol>
	<sodium>180</sodium>
	<carb>15</carb>
	<fiber>1</fiber>
	<protein>2</protein>
	<vitamins>
		<a>0</a>
		<c>10</c>
	</vitamins>
	<minerals>
		<ca>0</ca>
		<fe>0</fe>
	</minerals>
</food>

<food>
	<name>Soy Patties, Grilled</name>
	<mfr>Gardenproducts</mfr>
	<serving units="g">96</serving>
	<calories total="160" fat="45"/>
	<total-fat>5</total-fat>
	<saturated-fat>0</saturated-fat>
	<cholesterol>0</cholesterol>
	<sodium>420</sodium>
	<carb>10</carb>
	<fiber>4</fiber>
	<protein>9</protein>
	<vitamins>
		<a>0</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>0</ca>
		<fe>0</fe>
	</minerals>
</food>

<food>
	<name>Truffles, Dark Chocolate</name>
	<mfr>Lyndon's</mfr>
	<serving units="g">39</serving>
	<calories total="220" fat="170"/>
	<total-fat>19</total-fat>
	<saturated-fat>14</saturated-fat>
	<cholesterol>25</cholesterol>
	<sodium>10</sodium>
	<carb>16</carb>
	<fiber>1</fiber>
	<protein>1</protein>
	<vitamins>
		<a>0</a>
		<c>0</c>
	</vitamins>
	<minerals>
		<ca>0</ca>
		<fe>0</fe>
	</minerals>
</food>

</nutrition>

## xlsx

In [4]:
import pandas as pd

In [5]:
url = "https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_50.xlsx"
df = pd.read_excel(url)

In [6]:
df

     0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125